### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by silence-tang** [Yukun-Huang/DreamWaltz-G#2]
Hi, this is a great work!

May I ask what's the training time of the canonical avatar learning stage if the rendering resolution is 1024x1024? Thanks!

**Comment by silence-tang** [comment]
By the way, if a 3090ti is enough to train the model?

**Comment by Yukun-Huang** [comment]
Hi tang, thanks for your interest in our work!
1. Unfortunately, our machine does not have enough GPU memory to support training at 1024x1024 resolution during the canonical avatar learning stage. We only use 1024x1024 resolution for inference.
2. Yes, I think 3090ti is enough to train the model, but you may still encounter OOM error when training some complex avatars, for example, those with huge dresses. The actual GPU memory usage depends on the size of the 3D shape.
