### ISSUE TITLE
Any tips or tricks to reduce random artifacting?

### ISSUE THREAD

**Issue by gt732** [Yukun-Huang/DreamWaltz-G#8]
Hi,

Any tips on reducing random artifacts in scenes? They seem to appear unpredictably with various prompts, even with both ControlNets enabled. I haven't pinpointed a specific trigger.

This is during Stage1 Nerf training.

![image](https://github.com/user-attachments/assets/a717951b-6cd7-445f-900e-e98d678f2112)

Thanks!

**Comment by xdobetter** [comment]
Hi, bro. I'm curious about what prompt you are using. I have tested many prompts, but I have never encountered such a situation.

**Comment by gt732** [comment]
@xdobetter hey! I've been playing with a ton of hyperparameters. It seems to happen most when I use Loras and longer prompts. Funny enough I recently discovered setting the guidance scale to 7.5 like normal image generation and I get WAY better results. I'm also using a custom SD1.5 checkpoint, juggernaut and dreamshaper.

Some of my results using guidance scale of 7.5


https://github.com/user-attachments/assets/a704d69e-3d13-443d-9379-c7681578f60b


https://github.com/user-attachments/assets/ee4bf4e4-1842-44a2-bbc3-26d7b2de5749

https://github.com/user-attachments/assets/0ba50222-ee0b-467c-aa24-e8f6a8feec92



https://github.com/user-attachments/assets/f3fe878f-d41d-45ec-bdc2-5cff701dcae0

**Comment by xdobetter** [comment]
Wow, its so cool, your result looks really good and very interesting. I'm curious if you used the corresponding Lora to generate characters like "Goku" and "Lara"

**Comment by gt732** [comment]
@xdobetter so for those no Lora’s were used just very simple prompts like “Kratos from god of war” …. Try using a different sd1.5 checkpoint like dreamshaper or juggernaut and set the guidance scale way down like 7

**Comment by xdobetter** [comment]
wowo~I see.
---- Replied Message ----
From ***@***.***> Date 10/30/2024 23:54 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [Yukun-Huang/DreamWaltz-G] Any tips or tricks to reduce random artifacting? (Issue #8) 
@xdobetter so for those no Lora’s were used just very simple prompts like “Kratos from god of war” …. Try using a different sd1.5 checkpoint like dreamshaper or juggernaut

**Comment by Yukun-Huang** [comment]
@gt732 
1. We too find that a small guidance scale (like 7.5) could produce smooth geometry (less artifacts), but a large guidance scale leads to more visual details.

2. Even if you do nothing, these artifacts may be eliminated in the second stage of NeRF training (512x512 resolution). We do have two ways to reduce the NeRF artifacts:
- The first way is to use sparse regularization constraints. We provide several options like `--nerf.[lambda_entropy | lambda_opacity | lambda_emptiness]`.
- The second way is to use a MLP-encoded background by setting `--nerf.bg_mode nerf`, instead of a gray background: `--nerf.bg_mode gray`.

**Comment by Yukun-Huang** [comment]
> @xdobetter hey! I've been playing with a ton of hyperparameters. It seems to happen most when I use Loras and longer prompts. Funny enough I recently discovered setting the guidance scale to 7.5 like normal image generation and I get WAY better results. I'm also using a custom SD1.5 checkpoint, juggernaut and dreamshaper.
> 
> Some of my results using guidance scale of 7.5
> 
>  000000_image.mp4 
>  000500_image.mp4 
>  000000_image.mp4 
>  000000_image.mp4

Cool! The models you trained seems to be better than mine...

**Comment by gt732** [comment]
@Yukun-Huang thanks for the tips! This was all done on a single 24GB 3090. I'm trying to find new ways to fine tune everything to get a good balance between quality and GPU requirements.

Closing this.
